name: publish

on:
  push:
    branches: [ main ]

env:
  image: ghcr.io/yoyozbi/twitbot

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker images
      run: | 
        docker build --build-arg opts="CGO_ENABLED=0 GOARCH=amd64" --build-arg ARCH=amd64 --tag ${{ env.image }}:amd64 .
        docker push ${{ env.image }}:amd64
        docker build --build-arg opts="CGO_ENABLED=0 GOARCH=arm64" --build-arg ARCH=amr64v8 --tag ${{ env.image }}:arm64 .
        docker push ${{ env.image }}:arm64
    - name: Create and publish manifest
      run: |
          docker manifest create  --amend ${{ env.image }} ${{ env.image }}:amd64 ${{ env.image }}:arm64
          docker manifest annotate ${{ env.image }} ${{ env.image }}:arm64 --os linux --arch arm64
          docker manifest annotate ${{ env.image }} ${{ env.image }}:amd64 --os linux --arch amd64 
          docker manifest push ${{ env.image }}
